# ATLAS - Hospital Data Cleaning

## Purpose

For this notebook, the goal is to clean the CMS Hospital General Information dataset and create a smaller dataset containing only hospitals located in New Jersey.

The cleaned hospital data will later be used as possible shipment destinations in the ATLAS dashboard.

## Step 1: Import Libraries

The first step is to import the Python libraries needed for this notebook.

Pandas will be used to load, clean, filter, and save the hospital dataset.

In [13]:
import pandas as pd

## Step 2: Load the Hospital Dataset

The Hospital General Information dataset comes from the Centers for Medicare & Medicaid Services (CMS).

This dataset contains information about hospitals across the United States, including their names, addresses, cities, states, ZIP codes, and other hospital-related information.

The raw dataset is stored in the `data/raw` folder.

In [14]:
hospital_df = pd.read_csv("../data/raw/Hospital_General_Information.csv")

## Step 3: Inspect the Dataset

Before cleaning the data, it is important to understand what the dataset looks like.

The following cells will display:

- The first few rows
- The number of rows and columns
- The names of all the columns

In [15]:
hospital_df.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Acute Care Hospitals,Government - Hospital District or Authority,...,1,9,1,NaN,15,15,NaN,10,10,NaN
1,010005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Acute Care Hospitals,Government - Hospital District or Authority,...,1,8,0,NaN,15,15,NaN,10,10,NaN
2,010006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,Acute Care Hospitals,Proprietary,...,1,8,0,NaN,15,15,NaN,10,9,NaN
3,010007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,Acute Care Hospitals,Voluntary non-profit - Private,...,0,3,2,NaN,15,5,NaN,10,7,NaN
4,010011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,Acute Care Hospitals,Voluntary non-profit - Private,...,1,5,2,29.0,15,10,29.0,10,7,29.0

In [16]:
hospital_df.shape

(5419, 38)

In [17]:
hospital_df.columns.tolist()

['Facility ID',
 'Facility Name',
 'Address',
 'City/Town',
 'State',
 'ZIP Code',
 'County/Parish',
 'Telephone Number',
 'Hospital Type',
 'Hospital Ownership',
 'Emergency Services',
 'Meets criteria for birthing friendly designation',
 'Hospital overall rating',
 'Hospital overall rating footnote',
 'MORT Group Measure Count',
 'Count of Facility MORT Measures',
 'Count of MORT Measures Better',
 'Count of MORT Measures No Different',
 'Count of MORT Measures Worse',
 'MORT Group Footnote',
 'Safety Group Measure Count',
 'Count of Facility Safety Measures',
 'Count of Safety Measures Better',
 'Count of Safety Measures No Different',
 'Count of Safety Measures Worse',
 'Safety Group Footnote',
 'READM Group Measure Count',
 'Count of Facility READM Measures',
 'Count of READM Measures Better',
 'Count of READM Measures No Different',
 'Count of READM Measures Worse',
 'READM Group Footnote',
 'Pt Exp Group Measure Count',
 'Count of Facility Pt Exp Measures',
 'Pt Exp Group Footnote',
 'TE Group Measure Count',
 'Count of Facility TE Measures',
 'TE Group Footnote']

The dataset has 5419 rows (each representing a hospital), and 38 columns providing different information about that hospital.

## Step 4: Filter for New Jersey Hospitals

Since this is a POC for J&J, ATLAS will focus only on logistics within New Jersey.

So, the full CMS dataset will be filtered to only hospitals where the state is listed as `NJ`.

In [18]:
nj_hospitals = hospital_df[hospital_df["State"] == "NJ"].copy()

nj_hospitals.shape

(78, 38)

In [19]:
nj_hospitals.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,Hospital Type,Hospital Ownership,...,Count of READM Measures Better,Count of READM Measures No Different,Count of READM Measures Worse,READM Group Footnote,Pt Exp Group Measure Count,Count of Facility Pt Exp Measures,Pt Exp Group Footnote,TE Group Measure Count,Count of Facility TE Measures,TE Group Footnote
3076,310001,HACKENSACK UNIVERSITY MEDICAL CENTER,30 PROSPECT AVE,HACKENSACK,NJ,7601,BERGEN,(551) 996-2000,Acute Care Hospitals,Voluntary non-profit - Private,...,2,5,4,NaN,15,15,NaN,10,8,NaN
3077,310002,NEWARK BETH ISRAEL MEDICAL CENTER,201 LYONS AVE,NEWARK,NJ,7112,ESSEX,(973) 926-7000,Acute Care Hospitals,Voluntary non-profit - Private,...,0,7,3,NaN,15,15,NaN,10,8,NaN
3078,310003,PALISADES MEDICAL CENTER,7600 RIVER RD,NORTH BERGEN,NJ,7047,HUDSON,(201) 854-5000,Acute Care Hospitals,Voluntary non-profit - Private,...,0,4,2,NaN,15,15,NaN,10,9,NaN
3079,310005,HUNTERDON MEDICAL CENTER,2100 WESCOTT DRIVE,FLEMINGTON,NJ,8822,HUNTERDON,(908) 788-6100,Acute Care Hospitals,Voluntary non-profit - Private,...,0,6,2,NaN,15,15,NaN,10,7,NaN
3080,310006,ST MARY'S GENERAL HOSPITAL,350 BOULEVARD,PASSAIC,NJ,7055,PASSAIC,(973) 365-4300,Acute Care Hospitals,Proprietary,...,1,5,1,NaN,15,15,NaN,10,8,NaN

After filtering the dataset, we are left with 78 hospitals that are based in New Jersey.

## Step 5: Select Relevant Columns

For this project, only the columns needed to identify hospital destinations and their locations will be kept:

- Facility ID
- Facility Name
- Address
- City/Town
- State
- ZIP Code
- County/Parish

In [21]:
columns_to_keep = [
    "Facility ID",
    "Facility Name",
    "Address",
    "City/Town",
    "State",
    "ZIP Code",
    "County/Parish"
]

nj_hospitals = nj_hospitals[columns_to_keep]

nj_hospitals.shape

(78, 7)

In [22]:
nj_hospitals.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish
3076,310001,HACKENSACK UNIVERSITY MEDICAL CENTER,30 PROSPECT AVE,HACKENSACK,NJ,7601,BERGEN
3077,310002,NEWARK BETH ISRAEL MEDICAL CENTER,201 LYONS AVE,NEWARK,NJ,7112,ESSEX
3078,310003,PALISADES MEDICAL CENTER,7600 RIVER RD,NORTH BERGEN,NJ,7047,HUDSON
3079,310005,HUNTERDON MEDICAL CENTER,2100 WESCOTT DRIVE,FLEMINGTON,NJ,8822,HUNTERDON
3080,310006,ST MARY'S GENERAL HOSPITAL,350 BOULEVARD,PASSAIC,NJ,7055,PASSAIC

## Step 6: Check for Missing Values

Next we will check for missing values which could cause problems later when the data is used for shipment destination or geographic analysis.

In [23]:
nj_hospitals.isnull().sum()

Facility ID      0
Facility Name    0
Address          0
City/Town        0
State            0
ZIP Code         0
County/Parish    0
dtype: int64

## Step 7: Reset the Index

After filtering the original dataset to New Jersey hospitals, the original row numbers were retained.

The index will be reset so the cleaned dataset has a simple sequential index starting from 0.

In [24]:
nj_hospitals = nj_hospitals.reset_index(drop=True)

nj_hospitals.head()

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish
0,310001,HACKENSACK UNIVERSITY MEDICAL CENTER,30 PROSPECT AVE,HACKENSACK,NJ,7601,BERGEN
1,310002,NEWARK BETH ISRAEL MEDICAL CENTER,201 LYONS AVE,NEWARK,NJ,7112,ESSEX
2,310003,PALISADES MEDICAL CENTER,7600 RIVER RD,NORTH BERGEN,NJ,7047,HUDSON
3,310005,HUNTERDON MEDICAL CENTER,2100 WESCOTT DRIVE,FLEMINGTON,NJ,8822,HUNTERDON
4,310006,ST MARY'S GENERAL HOSPITAL,350 BOULEVARD,PASSAIC,NJ,7055,PASSAIC

## Step 8: Save the Cleaned Dataset

The cleaned New Jersey hospital dataset will now be saved in the `data/processed` folder.

This processed file will be used later when ATLAS combines hospital locations with traffic-risk and shipment data.

In [25]:
nj_hospitals.to_csv(
    "../data/processed/nj_hospitals_clean.csv",
    index=False
)