# ATLAS - Traffic Data Cleaning

## Purpose

For this notebook, the goal is to clean the US Accidents dataset and create a smaller dataset containing only traffic incidents located in New Jersey.

The cleaned traffic data will later be used to identify transportation risk patterns in the ATLAS dashboard.

## Step 1: Import Libraries

The first step is to import the Python libraries needed for this notebook.

Pandas will be used to load, clean, filter, and transform the traffic dataset.

In [2]:
import pandas as pd

## Step 2: Load the Traffic Dataset

The US Accidents dataset comes from Kaggle and contains historical traffic incident data collected from transportation and traffic sources across the United States.

This dataset contains information about traffic incidents, including their location, severity, timing, roadway impact, and weather conditions.

The raw dataset is stored in the `data/raw` folder.

In [3]:
traffic_df = pd.read_csv("../data/raw/US_Accidents_March23.csv")

## Step 3: Inspect the Dataset

Before cleaning the data, it is important to understand what the dataset looks like.

The following cells will display:

- The first few rows
- The number of rows and columns
- The names of all the columns

In [4]:
traffic_df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [5]:
traffic_df.shape

(7728394, 46)

In [6]:
traffic_df.columns.tolist()

['ID',
 'Source',
 'Severity',
 'Start_Time',
 'End_Time',
 'Start_Lat',
 'Start_Lng',
 'End_Lat',
 'End_Lng',
 'Distance(mi)',
 'Description',
 'Street',
 'City',
 'County',
 'State',
 'Zipcode',
 'Country',
 'Timezone',
 'Airport_Code',
 'Weather_Timestamp',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Direction',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Weather_Condition',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Turning_Loop',
 'Sunrise_Sunset',
 'Civil_Twilight',
 'Nautical_Twilight',
 'Astronomical_Twilight']

The dataset has 7,728,394 rows (each representing a traffic incident), and 46 columns providing different information about that incident.

## Step 4: Filter for New Jersey Incidents

Since this is a POC for J&J, ATLAS will focus only on logistics within New Jersey.

So, the full US Accidents dataset will be filtered to only traffic incidents where the state is listed as `NJ`.

In [7]:
nj_traffic = traffic_df[traffic_df["State"] == "NJ"].copy()

nj_traffic.shape

(140719, 46)

In [8]:
nj_traffic.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
194249,A-194256,Source2,2,2016-11-30 16:37:24,2016-11-30 17:22:05,40.775616,-74.237305,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Day,Day,Day
194265,A-194272,Source2,2,2016-11-30 17:11:50,2016-11-30 17:56:38,40.944626,-74.100800,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Day,Day
194266,A-194273,Source2,2,2016-11-30 17:13:28,2016-11-30 18:13:14,40.846260,-74.042770,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Day,Day
194275,A-194282,Source2,3,2016-11-30 17:29:30,2016-11-30 18:14:16,40.641262,-74.205650,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Day,Day
194294,A-194301,Source2,2,2016-11-30 19:10:49,2016-11-30 20:10:39,40.957714,-73.975098,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Night,Night

After filtering the dataset, we are left with 140,719 incidents that are based in New Jersey.

## Step 5: Select Relevant Columns

For this project, only the columns needed to understand traffic incidents and their surrounding conditions will be kept:

- ID
- Severity
- Start Time
- End Time
- Start Latitude
- Start Longitude
- City
- County
- State
- ZIP Code
- Distance (mi)
- Temperature (F)
- Visibility (mi)
- Precipitation (in)
- Weather Condition

In [9]:
traffic_columns = [
    "ID",
    "Severity",
    "Start_Time",
    "End_Time",
    "Start_Lat",
    "Start_Lng",
    "City",
    "County",
    "State",
    "Zipcode",
    "Distance(mi)",
    "Temperature(F)",
    "Visibility(mi)",
    "Precipitation(in)",
    "Weather_Condition"
]

nj_traffic = nj_traffic[traffic_columns]

nj_traffic.shape

(140719, 15)

In [10]:
nj_traffic.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,City,County,State,Zipcode,Distance(mi),Temperature(F),Visibility(mi),Precipitation(in),Weather_Condition
194249,A-194256,2,2016-11-30 16:37:24,2016-11-30 17:22:05,40.775616,-74.237305,Orange,Essex,NJ,07050-1520,0.01,55.0,2.5,0.02,Light Rain
194265,A-194272,2,2016-11-30 17:11:50,2016-11-30 17:56:38,40.944626,-74.100800,Fair Lawn,Bergen,NJ,07410-5145,0.01,54.0,4.0,0.00,Rain
194266,A-194273,2,2016-11-30 17:13:28,2016-11-30 18:13:14,40.846260,-74.042770,Little Ferry,Bergen,NJ,07643-1830,0.01,54.0,4.0,0.00,Rain
194275,A-194282,3,2016-11-30 17:29:30,2016-11-30 18:14:16,40.641262,-74.205650,Elizabeth,Union,NJ,07202,0.01,54.5,4.0,0.01,Light Drizzle
194294,A-194301,2,2016-11-30 19:10:49,2016-11-30 20:10:39,40.957714,-73.975098,Demarest,Bergen,NJ,07627-1904,0.01,54.0,4.0,0.01,Rain

## Step 6: Check for Missing Values

Next we will check for missing values which could cause problems later when the data is used for traffic-risk and geographic analysis.

In [11]:
nj_traffic.isnull().sum()

ID                       0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
City                     0
County                   0
State                    0
Zipcode                  1
Distance(mi)             0
Temperature(F)        2792
Visibility(mi)        5216
Precipitation(in)    34682
Weather_Condition     3603
dtype: int64

In [12]:
nj_traffic = nj_traffic.dropna(subset=["Zipcode"])

nj_traffic.isnull().sum()

ID                       0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
City                     0
County                   0
State                    0
Zipcode                  0
Distance(mi)             0
Temperature(F)        2791
Visibility(mi)        5215
Precipitation(in)    34681
Weather_Condition     3602
dtype: int64

The core traffic fields needed for ATLAS, including incident ID, severity, timing, and location, contain no missing values.

One incident is missing a ZIP code, so that row will be removed.

Some weather-related fields contain missing values. These rows will be kept because the traffic incident itself is still useful, even if some weather information is unavailable.

## Step 7: Create Time-Based Fields

The traffic dataset includes start and end timestamps for each incident.

These timestamps will be converted into a datetime format so ATLAS can analyze traffic patterns by:

- Hour of day
- Day of week
- Incident duration

In [15]:
nj_traffic["Start_Time"] = pd.to_datetime(
    nj_traffic["Start_Time"],
    format="mixed"
)

nj_traffic["End_Time"] = pd.to_datetime(
    nj_traffic["End_Time"],
    format="mixed"
)

nj_traffic["Hour"] = nj_traffic["Start_Time"].dt.hour
nj_traffic["Day_of_Week"] = nj_traffic["Start_Time"].dt.day_name()

nj_traffic["Incident_Duration_Min"] = (
    nj_traffic["End_Time"] - nj_traffic["Start_Time"]
).dt.total_seconds() / 60

nj_traffic[
    ["Start_Time", "End_Time", "Hour", "Day_of_Week", "Incident_Duration_Min"]
].head()

,Start_Time,End_Time,Hour,Day_of_Week,Incident_Duration_Min
194249,2016-11-30 16:37:24,2016-11-30 17:22:05,16,Wednesday,44.683333
194265,2016-11-30 17:11:50,2016-11-30 17:56:38,17,Wednesday,44.800000
194266,2016-11-30 17:13:28,2016-11-30 18:13:14,17,Wednesday,59.766667
194275,2016-11-30 17:29:30,2016-11-30 18:14:16,17,Wednesday,44.766667
194294,2016-11-30 19:10:49,2016-11-30 20:10:39,19,Wednesday,59.833333

## Step 8: Validate Incident Duration

Before using incident duration in later analysis, the values will be reviewed for possible data issues.

This check will look for:

- Negative durations
- Extremely long durations
- General summary statistics

In [16]:
nj_traffic["Incident_Duration_Min"].describe()

count    1.407180e+05
mean     2.178159e+02
std      8.151714e+03
min      4.933333e+00
25%      3.398333e+01
50%      8.419167e+01
75%      1.331833e+02
max      1.039752e+06
Name: Incident_Duration_Min, dtype: float64

In [17]:
(nj_traffic["Incident_Duration_Min"] < 0).sum()

np.int64(0)

In [18]:
nj_traffic.nlargest(
    10,
    "Incident_Duration_Min"
)[
    ["ID", "Start_Time", "End_Time", "Incident_Duration_Min"]
]

,ID,Start_Time,End_Time,Incident_Duration_Min
3510279,A-3520162,2016-05-05 14:47:55,2018-04-27 16:00:00,1.039752e+06
3496089,A-3505972,2016-07-01 12:51:02,2018-04-27 16:00:00,9.577890e+05
3500134,A-3510017,2016-07-13 13:02:27,2018-04-27 16:00:00,9.404976e+05
3497306,A-3507189,2016-07-17 11:58:45,2018-04-27 16:00:00,9.348012e+05
5656646,A-5699248,2019-10-02 12:50:00,2021-07-03 02:57:45,9.210078e+05
3468180,A-3478063,2016-09-21 04:40:23,2018-04-27 16:00:00,8.401996e+05
3456542,A-3466425,2016-10-28 00:35:05,2018-04-27 16:00:00,7.871649e+05
3457360,A-3467243,2016-10-28 00:35:05,2018-04-27 16:00:00,7.871649e+05
3458186,A-3468069,2016-11-01 19:35:21,2018-04-27 16:00:00,7.802647e+05
3463041,A-3472924,2016-11-17 15:12:41,2018-04-27 16:00:00,7.574873e+05

No negative incident durations were found.

Most incidents have reasonable durations, with a median duration of about 84 minutes. However, a small number of records contain extremely long durations lasting months or even years.

These extreme values are likely not useful for normal traffic-risk analysis. The incidents will remain in the dataset, but unusually long durations will be excluded when incident duration is analyzed.

## Step 9: Identify Valid Incident Durations

Some traffic incidents contain unusually long duration values.

For ATLAS, incident durations of 24 hours or less will be considered reasonable for normal traffic-risk analysis.

Longer incidents will remain in the dataset, but their duration values will not be used when analyzing typical incident duration.

In [19]:
nj_traffic["Valid_Duration"] = (
    nj_traffic["Incident_Duration_Min"] <= 1440
)

nj_traffic["Valid_Duration"].value_counts()

Valid_Duration
True     140428
False       290
Name: count, dtype: int64

Out of 140,718 New Jersey traffic incidents, 140,428 have durations of 24 hours or less.

Only 290 incidents exceed the 24-hour cutoff, so most of the dataset contains reasonable incident duration values.

These longer incidents will remain in the dataset, but they will not be used when analyzing typical incident duration.

## Step 10: Reset the Index

After filtering and cleaning the dataset, the original row numbers are no longer sequential.

The index will be reset so the cleaned traffic dataset has a simple row index starting from 0.

In [20]:
nj_traffic = nj_traffic.reset_index(drop=True)

nj_traffic.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,City,County,State,Zipcode,Distance(mi),Temperature(F),Visibility(mi),Precipitation(in),Weather_Condition,Hour,Day_of_Week,Incident_Duration_Min,Valid_Duration
0,A-194256,2,2016-11-30 16:37:24,2016-11-30 17:22:05,40.775616,-74.237305,Orange,Essex,NJ,07050-1520,0.01,55.0,2.5,0.02,Light Rain,16,Wednesday,44.683333,True
1,A-194272,2,2016-11-30 17:11:50,2016-11-30 17:56:38,40.944626,-74.100800,Fair Lawn,Bergen,NJ,07410-5145,0.01,54.0,4.0,0.00,Rain,17,Wednesday,44.800000,True
2,A-194273,2,2016-11-30 17:13:28,2016-11-30 18:13:14,40.846260,-74.042770,Little Ferry,Bergen,NJ,07643-1830,0.01,54.0,4.0,0.00,Rain,17,Wednesday,59.766667,True
3,A-194282,3,2016-11-30 17:29:30,2016-11-30 18:14:16,40.641262,-74.205650,Elizabeth,Union,NJ,07202,0.01,54.5,4.0,0.01,Light Drizzle,17,Wednesday,44.766667,True
4,A-194301,2,2016-11-30 19:10:49,2016-11-30 20:10:39,40.957714,-73.975098,Demarest,Bergen,NJ,07627-1904,0.01,54.0,4.0,0.01,Rain,19,Wednesday,59.833333,True

## Step 11: Save the Cleaned Dataset

The cleaned New Jersey traffic dataset will now be saved in the `data/processed` folder.

This processed file will later be used in the ATLAS analysis to identify traffic-risk patterns and support shipment risk monitoring.

In [21]:
nj_traffic.to_csv(
    "../data/processed/nj_traffic_clean.csv",
    index=False
)